export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_ERROR = 'BOTAO_CLICADO_ERROR';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
